### ISSUE TITLE
[BUG] Randomized names fail on scenes with specifically defined/worded grid scale and units

### ISSUE THREAD

**Issue by miromonti** [Moerill/token-mold#102]
This is a weird one. A scene's grid scale is set to "50 ft" and Token Mold's name randomizer won't work. This feature works elsewhere in the game, but not with this scene. 

I turned off all other modules to test TM and discovered that a grid scale of 41 or greater and units of "ft", "ft.", or "feet" disables the name randomizer. 

I eventually tested on a new, blank scene and reproduced the issue:
1. Make grid scale 41 or greater
2. Make grid units "ft", "ft.", or "feet"
3. Place a token
4. The token's name is unchanged

The name randomizer has no issue if grid scale is 40 or less with grid units "ft", "ft.", or "feet". It also works if grid units is _anything else._ I used "fe", "fte", "fet", "mi", "yd", "bananas", etc., and TM's name randomizer performed as expected, no matter the number for grid scale.

Maybe just me?

 - MacOS
 - Chrome 92.0.4515.107
 - Edge 92.0.902.55
 - Firefox 90.0.2
 - FVTT 0.8.8
 - Module version 2.13.1

**Comment by Geekswordsman** [comment]
Perhaps this was a bug as the result of something in Foundry v0.8.8?

Attempted to reproduce in v0.8.9, Token Mold v2.13.1, and Chrome following the exact steps provided and token name is modified as expected.

**Comment by miromonti** [comment]
You might be right about Foundry v0.8.8. I retested now with v0.8.9 and latest Token Mold v2.14.0 and tokens rename as expected.

Whatever that was doesn't exist now. (Maybe was just me?) So, not an issue anymore.
