### ISSUE TITLE
[BUG] vehicle tokens not respecting prototype token image scale

### ISSUE THREAD

**Issue by modzy2** [Moerill/token-mold#104]
**Describe the bug**
For a Vehicle type of actor, with a prototype token image scale set to other than 1, as the token is dropped onto the canvas, it doesn't use the scaling.  (ie; it gets reset to 1 on the placed token)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new actor of type Vehicle
2. Set the scale of the prototype token to other than 1
3. Drop the token onto the canvas, note scale is 1

**Expected behaviour**
The placed token should inherit the scale of the prototype token scale value

**Module incompatibilities**
This happens with only token mold active.

**Screenshots/GIFs/Videos**
> A picture is worth a thousand words.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome
 - FVTT Version 0.8.8
 - Module version 2.13.1

**Comment by sophiechiabatta** [comment]
Quick note that I was also seeing this behavior and found the solution in [this](https://github.com/Moerill/token-mold/issues/79) prior bug report. From within Token Mold options go to the System Specific tab and disable "Set Token size to creature size and scaled to map scale."

**Comment by Moerill** [comment]
yep, working as intended as sophichiabatta mentioned.
