### ISSUE TITLE
[FEATURE] More control over stats overlay

### ISSUE THREAD

**Issue by RexMan85** [Moerill/token-mold#106]
Hi, I really like the stats overlay feature of the module, and I use it a lot, but I'd like to have more control over the stats that are overlayed.
The two main things I'd want are:

- display flying speed, unless it's zero, then just display walking speed, and have a different icon for each of them. e.g. for a goblin it would display [shoes] 30, but for a dragon it would display [wings] 60.
- Display more stats for larger monsters. I only display 3 stats because otherwise it too many for Medium creatures. However for large or huge creatures there is a lot of unused space to use for more stats. It'd be nice if there was an option to choose more stats for larger monsters that have space to display them

**Comment by Moerill** [comment]
Hi, thanks for the feature request.

I won't be implementing those though. I currently don't have enough time to work on any modules, but planned a big rework of token mold, introducing more flexibility, while probably removing the overlay.  
Why? cause there is a better, more specialized module for this usecase: [token tooltip alt](https://github.com/bmarian/token-tooltip-alt). There your features could be done using the scripting thingy, if not implemented already.
