### ISSUE TITLE
[BUG] Modify Default Config Shows No Choices for Attribute Bars

### ISSUE THREAD

**Issue by SmokeRaven667** [Moerill/token-mold#107]
The Modify Default Config tab does not show any choice for the attribute bars. 

I want to be able to Overwrite and set the Bar 1 Attribute to Strength, and Bar 2 to Agility, for the Forbidden Lands game system.

**To Reproduce**
1. Launch Game World that uses Forbidden Lands system with Token Mold installed and enabled.
2. Click Actor tab
3. Click Gear for Token Mold and go to Modify Default Config tab
4. Note no options in Bar 1 Attribute dropdown (see screen shot).

**Expected behavior**
I hoped to see the actor attributes from the Forbidden Lands actor sheet as choices for the Bar attributes.

**Screenshots/GIFs/Videos**
![image](https://user-images.githubusercontent.com/79171846/132972817-50c47f1f-37e6-4e2c-a173-6edf9033f82d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - FVTT Version 0.8.9
 - Module version 2.13.0

**Comment by Geekswordsman** [comment]
This may have been a bug as a result of an earlier version of the system, or was fixed in v2.13.1

Just attempted to reproduce but was unable to.

OS: Windows 10
Browser: Chrome v96.0.4664.45 (64 bit)
FVTT Version 0.8.9
Forbidden Lands v7.1.5
Module v2.13.1
