### ISSUE TITLE
[FEATURE] Disable naming for specific actors

### ISSUE THREAD

**Issue by ashlacon** [Moerill/token-mold#109]
I love the abilities to have randomly generated names, so every single npc isn't just "Guard" or "Goblin", however when dropping in NPCs like companions or reoccurring NPCs I often forget to disable the option, which leads to "Wait wasn't his name something else? Lemme check my notes" Its not the biggest problem in the world, a simple copy /paste of the name from the actor sheet or dropping the token in a second time after disabling name fixes it, but it would be nice.

Something like a button on the NPC sheet that says "Do not randomly name" or even a symbol we could put in the NPCs name like !Ferda Rumblefoot and when the token is placed in a scene if there is a ! as the first character, it only removes the ! rather than generate a new name.

**Comment by Geekswordsman** [comment]
There is really no good way to implement this without a very complex UX :(
