### ISSUE TITLE
[BUG] tokens/actors without names can be created

### ISSUE THREAD

**Issue by Drental** [Moerill/token-mold#111]
**Describe the bug**
![image](https://user-images.githubusercontent.com/74384067/142724793-faa489fb-0045-4622-8436-7000434f9c61.png)
![image](https://user-images.githubusercontent.com/74384067/142724795-219ac269-6786-469e-a725-9d5e13692d9d.png)

**To Reproduce**
if you turn off counting number suffix and random adjective, then change base name to remove and try and drag a token onto your map, it just breaks your game.

**Expected behavior**
set a name that contains at least one character. Maybe copy the type and use that as the name?

**Comment by Geekswordsman** [comment]
This is an understandable bug as Foundry absolutely expects a name, but with this setup the program is literally trying to do what is asked of it.

I believe the best solution would be to _not_ allow base name to be set to remove if add counting numbers and random adjectives are both disabled as well.
