### ISSUE TITLE
[BUG] Installing 2.15.0 actually installs 2.14.0

### ISSUE THREAD

**Issue by cs96and** [Moerill/token-mold#118]
I just updated from 2.14.0 to 2.15.0.  Foundry popped up a dialog about an updated manifest URL, so I clicked yes.  The instaled version is still 2.14.0 though.  I tried uninstalling and re-installing, but it still installs v2.14.0

**Comment by foxreinhold** [comment]
The module.json is just still ID'ing it as 2.14.0, but the files are for 2.15.0.  He just needs to update the module.json

**Comment by cs96and** [comment]
The download link in the 2.15.0 manifest file also points to the 2.14.0 zip file, so I think 2.14.0 is actually getting installed.

https://raw.githubusercontent.com/Moerill/token-mold/v2.15.0/module.json

```json
"download": "https://github.com/Moerill/token-mold/releases/download/v2.14.0/v2.14.0.zip",
```

**Comment by Geekswordsman** [comment]
Sorry all, somehow in all the updates yesterday this got overlooked 😓 

Updating and fixing now.
