### ISSUE TITLE
Foundry Server Debug Log shows warning...

### ISSUE THREAD

**Issue by karpana** [Moerill/token-mold#119]
When I restart my Foundry instance, this message is continually present in the `debug.log` file.

Foundry Version: v9 build 249
System: PF1
Host/Server Operating System: Raspberry Pi 4.

```
{"level":"warn","message":"Package token-mold contains 1 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2022-02-07 09:18:05"}
```

**Comment by DrMcCoy** [comment]
Support for "entity"-only packs lists will be removed with Foundry VTT V10: https://gitlab.com/foundrynet/foundryvtt/-/issues/6666
