### ISSUE TITLE
Overlay disappears

### ISSUE THREAD

**Issue by PyroFD3S** [Moerill/token-mold#12]
I think I have the sort of the same issue as issue#11 with overlays not showing 
My issues is that after I press ALT a few times and highlight a token, they stop showing up until I refresh the browser

It seems that in the config for the overlay sometimes disappears too, when I go to look at it, it is, it's a blank tab

![tokenmold](https://user-images.githubusercontent.com/6959258/82742934-dcf45f00-9d18-11ea-9ebe-74220628f6dd.png)

**Comment by SalieriC** [comment]
This appears to be a conflict with Combat Utility Belt ( https://github.com/death-save/combat-utility-belt ).
If this could be patched I'd be rather grateful. =)

**Comment by Moerill** [comment]
hmmm
sorry i don#t have the time to debug interactions with another module in the near future - especially not one so monstrous as CUB.
Also its a rather strange interaction,  feels more like some strange stuff CUB is doing....

**Comment by Moerill** [comment]
(this doesn't mean i won't fix this, just not in the next few weeks)

**Comment by Moerill** [comment]
nevermind, found the culprit.
As expected its CUBs fault... :p (at least in my opinion.)
brought the issue to errationals attention, now its in his hands.
