### ISSUE TITLE
[BUG] Customizations options reset when opening module configuration

### ISSUE THREAD

**Issue by GabrielOsvair** [Moerill/token-mold#128]
**Describe the bug**
I only use the mod to add the numbers to the tokens, but whenever I open the module configuration, the token customization options are unchecked.

**Expected behavior**
Do not reset options when opening settings

**Desktop (please complete the following information):**
```
Foundry Virtual Tabletop: Version 9, 9.269
Game System: dnd5e, 1.6.3
Active Modules: 72
Performance Mode: 3

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 4200 x 4200 | Grid Size: 140 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 0

Actors: 124 | Items: 89 | Journal: 29 | Rollable Tables: 37 |
Playlists: 1 | Compendium Packs: 59 | Chat Messages: 0
```

**Comment by Geekswordsman** [comment]
Could you please be more specific about what is not keeping?

I have attempted to reproduce but all settings remain despite refreshes or changing scenes.

Would also request that you verify this behavior with all other modules disabled.
