### ISSUE TITLE
Token mold is not showing up in the Configure Modules tab

### ISSUE THREAD

**Issue by inkdreams** [Moerill/token-mold#133]
I have token mold enabled and it's working, I just can't configure anything. TM seems to not be showing up at all in the configuration settings of the system settings. I don't know if there's something I'm doing wrong, but I've removed all modules except token mold and it is not showing up.

**Comment by YuanRamirez** [comment]
All Token Mold settings can be found at the top of the "Actors Directory" tab.
![image](https://user-images.githubusercontent.com/24588007/187932018-1bfe7089-d096-4d81-ab56-9223e53225ed.png)
