### ISSUE TITLE
[BUG] "Apply settings to unlinked tokens only" not working for stat overlay

### ISSUE THREAD

**Issue by YuanRamirez** [Moerill/token-mold#134]
**Describe the bug**
The "Apply settings to unlinked tokens only" checkbox state is not respected for the display of the stat overlay.

**To Reproduce**
1. set up stat overlay
2. check the "apply settings to unlinked tokens only" checkbox
3. get the overlay to show, which can be a hassle (switching scenes usually works)
4. observe that linked tokens also display the stat overlay

**Expected behavior**
Since the checkbox is displayed in a all-encompassing manner, I'd assumed it also applies to the overlay.

**Screenshots/GIFs/Videos**
![bugreport2](https://user-images.githubusercontent.com/24588007/187938148-bf3ea6ad-f76e-4b06-80b9-d759ddad72c5.jpg)

![bugreport](https://user-images.githubusercontent.com/24588007/187938193-f3fa1f0e-ee33-4ba6-bf98-ff6c3929cc94.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - FVTT Version : Version 9, Build 280
 - Module version: 2.15.2

**Additional context**
I have a different module, Monk's Tokenbar, to track my PCs' passive Perception etc. but I absolutely abhor having to juggle NPC sheets on the little screen real estate I have. Given how comparatively little space on the screen Token Mold's overlay takes up, I want it to be able to see important stats for RP situations, like passive Insight and passive Perception, without having to open a dozen NPC sheets. But I want my players to be able to see their tokens at all times as clearly as possible.

**Comment by Geekswordsman** [comment]
Token Mold actually completely ignored the "Unlinked Only" setting for the overlay - it wasn't documented that this was the case.

The layout of the current setup menu doesn't this intuitive - the latest update will instead provide a new checkbox under the Overlay where you can choose to enable or disable it for linked tokens - this should fill the gap here until things are overhauled in v3.
