### ISSUE TITLE
Actors Scaling to Zero

### ISSUE THREAD

**Issue by multiplenerdgasms** [Moerill/token-mold#135]
I'm having an issue since updating to v10 of Foundry in which new actors dragged to a scene randomly set the token scale to 0. This isn't happening with any specific actor (I can drag the actor again and there's a chance it will be 0 or 1), and it is occurring even if Token Mold is the only active module.

I've turned off all module features that might impact token scale, but the issue persists.

**Comment by Geekswordsman** [comment]
Hrm... I really can't reproduce this - and all scales are currently set to have a minimum size.

Are you able to give any additional information?

Foundry version
System and System Version
Token Mold version
Scene Information (grid size & units)

**Comment by multiplenerdgasms** [comment]
> Hrm... I really can't reproduce this - and all scales are currently set to have a minimum size.
> 
> Are you able to give any additional information?
> 
> Foundry version System and System Version Token Mold version Scene Information (grid size & units)

This seems to have stopped being an issue in one of the subsequent updates, as I can no longer reproduce it either.
