### ISSUE TITLE
[BUG] missing configuration

### ISSUE THREAD

**Issue by steveculshaw** [Moerill/token-mold#143]
**Using the template**  
Cannot access any configuration options

**Describe the bug**
I've successfully installed the module, and I can drag monsters onto a scene, and they have their names updated, so I have "Cunning Goblin (2)". 
But I cannot access any configuration options in the Configure Settings, Module Settings.

**Expected behavior**
Some sort of configuration section

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser both Chrome and Edge
 - FVTT Version v9.280
 - Module version 2.15.4

![image](https://user-images.githubusercontent.com/64320/191091122-34f03418-6ade-478d-b730-dde2f6fbd453.png)

**Comment by steveculshaw** [comment]
Ah ha ... the Token Mold configuration isn't in Configure Game Settings / Module Settings

It's in the Actors Directory 

![image](https://user-images.githubusercontent.com/64320/191258211-0b38ae2c-ea8a-4f09-a948-582e901af77c.png)

Could we add this to the readme 
_(Actually by "we", I mean "you", as I don't know how to submit changes)_

**Comment by Geekswordsman** [comment]
I'm looking to adjust this in v3 and include access to the options via the standard configure settings menu :)

Part of #140
