### ISSUE TITLE
[BUG] Warning messages with v2.15.4 under v10.286

### ISSUE THREAD

**Issue by steveculshaw** [Moerill/token-mold#144]
**Describe the bug**
Warning messages in the console ...

[token-mold] The module "token-mold" contains "dependencies" which is deprecated in favor of "relationships.requires"
#logPackageWarnings @ setup.js:145
setup.js:145 
        
[token-mold] module "token-mold" contains "system" which is deprecated in favor of "relationships.systems"

**To Reproduce**
Load module

**Expected behavior**
No warning

**Screenshots/GIFs/Videos**
![image](https://user-images.githubusercontent.com/64320/192166379-93897bd9-d8a6-4eaf-860c-2e3c766d94bd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome & Edge
 - FVTT Version: 10.286
 - Module version: 2.15.4

**Comment by Geekswordsman** [comment]
These are left-over from v9 compatibility :)

These may not go away before v3, but I'll leave the issue open for tracking in case I need to do a minor patch before v3 is completed.

**Comment by HippyCraig** [comment]
Im also seeing the same issue

**Comment by adamj777** [comment]
Confirming for FVTT 10.291 as well. Thanks!
