### ISSUE TITLE
[BUG] modify default config settings do not apply pathfinder 2e

### ISSUE THREAD

**Issue by bogga** [Moerill/token-mold#147]
**Describe the bug**
I have random scale multiplier and random mirroring enabled in Modify Default Config and while other options from Modify Default Config apply, these do not.
![image](https://user-images.githubusercontent.com/25640047/196042445-a70d5bbe-fb95-4c5c-a366-b72412be70dc.png)

System is pathfinder 2e, versions are:
Foundry 10.286
Pathfinder 2e 4.2.6
Token Mold 2.15.4

**To Reproduce**
1. create Modify Default Config behaviour
2. drag an unlinked creature onto the board

**Expected behavior**
The token's scale is linked to the 2e system so while I wouldn't necessarily expect that to work, I would expect the token to be randomly mirrored horizontally

**Module incompatibilities**
I have tried this in a test world with only Token Mold enabled as a module and it didn't work.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - FVTT Version 10.286
 - Module version 2.15.4

**Additional context**
More than happy to reply & answer any questions, provide data files, etc

**Comment by adotor** [comment]
The same happens in DnD5e for the attribute bars. The value for the visibility of the bars is set but the value the bar represents is not.

Browser: Vivaldi
FVTT Version: 10.288
DnD5e Version: 2.0.3
Module Version: 2.15.4

**Comment by jerry2478** [comment]
> The same happens in DnD5e for the attribute bars. The value for the visibility of the bars is set but the value the bar represents is not.
> 

Same in Shadowdark System
Browser: Edge FVTT Version: 11.315 SD Version: 1.6.2 Module Version: 2.20.3

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
