### ISSUE TITLE
TypeError when mousing over a token without a Represented Actor

### ISSUE THREAD

**Issue by RedReign** [Moerill/token-mold#15]
`token-mold.js:33 Uncaught (in promise) TypeError: Cannot read property 'permission' of null`

It's a harmless error, but appears in the ~~chatlog~~ console log whenever a token is hovered over, or stops being hovered over.
Also occurs when the Alt key is pressed, for each token on the scene without a Represented Actor set.

**Comment by Moerill** [comment]
It appears in the chat log?

this one is actually known and i disregarded it, since to my knowledge tokens without actors are not supposed to "really exist". (like they have quite some missing functionality, don#t they?)

**Comment by RedReign** [comment]
Sorry, I meant console log. Miswrote that!

I like showing where my players are with a "you are here" token on the regional map. However, said token doesn't really need actor data - just a simple image. That's the only reason I've noticed this issue.

**Comment by Moerill** [comment]
i'll try to remember it and finally fix it for next release.
