### ISSUE TITLE
[Compatibility]  Token-Hud-Wildcard

### ISSUE THREAD

**Issue by InstantZzz** [Moerill/token-mold#150]
Hello,

I am not sure if I sure label my issue as _bug_ and I am not sure where the issue lies. I would make a post about this on their page as well but the fork (mentioned below) does not have an _issue_ tab.

I am using FVTT v10.291 and I am running Pathfinder 2E v4.5.0
I am using Token-Hud-Wildcard v1.7.1, this is a fork of the original module as the original is not V10 compatible.

Token-Hud-Wildcard has a feature that allows the owner of a token to set a Default image for their wildcard tokens. While I have both this module (Token-Mold v2.15.4) and Token Hud Wildcard v1.7.1, my default wildcard images stop functioning. This causes my tokens to functions as normal wildcard image.

**Comment by Geekswordsman** [comment]
This is likely due to the way TokenMold overrides the data coming in when it creates a Token.

This will be handled differently in v3 of Token Mold - but for now this is indeed a bug in the way Token Mold manages token data.

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
