### ISSUE TITLE
Setting "Random Scale Multiplier" Not Functional (5e System)

### ISSUE THREAD

**Issue by smturg** [Moerill/token-mold#151]
DESCRIPTION:
When attempting to create a token with the setting Random Scale Multiplier ticked "on" and set to a particular value - no scaling is applied when the token is dragged into the scene.

TO REPRODUCE
1) Tick setting "Random Scale Multiplier" on in Token Mold Settings.
2) Set scale to 0.5 in each box (or anything else; I tested with multiple values)
2) Tick "Config" on in Token Mold Bar (above Actors List in Foundry).
3) Drag a non-linked character onto the scene canvas.

EXPECTED BEHAVIOR
1) Token is created on canvas at 0.5 scale.

MODULE INCOMPATIBILITIES
- None - bug persists with all other modules inactive.

VIDEO
[Video](https://drive.google.com/file/d/19erMj4RvHYI3ofOjGHe7dAdkX2mqnzV8/view?usp=sharing)

SPECS
 - OS: Windows 11 Home
 - Browser: Chrome
 - FVTT Version: 10, Build 292
 - Module version: 2.15.4

ADDITIONAL CONTEXT:
This seems to be a problem since migrating from v9 to v10. I would imagine something in v10 may be interfering with scaling. Thanks in advance for any assistance you may be able to provide!

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
