### ISSUE TITLE
[BUG] Getting errors w/ 10.291 in Starfinder 0.22.1

### ISSUE THREAD

**Issue by MakaPhil** [Moerill/token-mold#152]
**Describe the bug**
Dragging a token onto the battle map does not preface or append the token name. This seems to be due to the fact that the module is not able to link to any of the dictionaries or rollable tables.

This does produce an error as follows:
actor.js:38 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pack')
[Detected 2 packages: system:sfrpg, token-mold]
    at new ActorSFRPG (actor.js:38)
    at TokenMold._getBarAttributes (token-mold.js:941)
    at Object.fn (token-mold.js:90)
    at Function.#call (foundry.js:724)
    at Function.callAll (foundry.js:681)
    at Game.setupGame (foundry.js:7952)
    at async Game._initializeGameView (foundry.js:8999)
    at async Game.initialize (foundry.js:7825)

**To Reproduce**
1. Install system: Starfinder 0.22.1
2. With Token-Mold enabled
3. Drag an actor from the Actors tab on to a battle map, seems to be any type of actor

**Expected behavior**
The token dragged onto the battle map gets an adjective assigned.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - FVTT Version 10.291
 - Module version 2.15.4

**Additional context**
I'm not sure if you accept pull requests, but I've solve the issue for myself, just wanted to file this bug so that you're aware.

Thanks for the great module!

**Comment by Geekswordsman** [comment]
Current version is frozen; the codebase is getting overhauled for v3 and I will make sure this is not an issue.
