### ISSUE TITLE
[BUG] Settings Save Button unclickable when Window Controls module is enabled

### ISSUE THREAD

**Issue by FeistyMango** [Moerill/token-mold#158]
**Describe the bug**
When clicking the Save and Close button in the Settings dialog, it does not perform the save action. Rather, it fires the Window Controls' minimize event handler instead.

**To Reproduce**
1. Enable the Windows module
2. Open the Actors tab
3. Click the Settings button for token-mold
4. Save button will be combined with the _ button for Window Controls module
5. Clicking this button triggers the Windows module event handler rather than running the save handler

**Expected behavior**
The Settings dialog window places the save button in the upper right corner. From a UX standpoint, this is pretty uncommon to place buttons in the corner locations of a dialog box. I think it was a reasonable UX choice by the Windows module to place its icons in that area as it's specifically trying to emulate OS window functionality. Rather a fixed position button within the form would be more standard.

**Module incompatibilities**
This is an integration bug with modules like Windows that place things in the corner of the dialog header across all dialogs.
https://github.com/saif-ellafi/foundryvtt-window-controls

**Screenshots/GIFs/Videos**
![image](https://user-images.githubusercontent.com/3461388/220175987-e0fd3b84-33da-48f5-9c09-3877722333e2.png)
![image](https://user-images.githubusercontent.com/3461388/220176398-e35c7811-4637-40e5-9c79-03012e053bc2.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser 110.0.5481.100 (Official Build) (64-bit)
 - FVTT Version 10.291
 - Module version: 2.15.4

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
