### ISSUE TITLE
[BUG] Conflict with Warpgate/PF2e Animations

### ISSUE THREAD

**Issue by MrVauxs** [Moerill/token-mold#159]
**Describe the bug**
I had reports of users trying to use the **PF2e Animations** summon feature with Token Mold enabled.
With Warpgate having created the token, this module conflict causes the token data to be practically overwritten by Token Mold, resulting in this:
![image](https://user-images.githubusercontent.com/32039708/220755388-d7593a50-93fb-460f-a70f-4269ea253a53.png)

**To Reproduce**
1. Summon an Unlinked Token with Warpgate (`warpgate.spawn("Actor Name")` should be enough)

**Expected behavior**
The name-changing behavior not overriding all token data.

**Module incompatibilities**
Warpgate

**Additional context**
[Existing Issue on Warpgate](https://github.com/trioderegion/warpgate/issues/123)

**Comment by MrVauxs** [comment]
While Token Mold is doing what it's told to do, it breaks half the Summoning of PF2e Animations.
If there is a way to disable Token Mold's modifications to specific tokens, I'm open to implementing them.

**Comment by Geekswordsman** [comment]
This is a known issue that will be resolved in the v3 overhaul :)
