### ISSUE TITLE
[BUG] Issue with Token Variant Art (TVA)

### ISSUE THREAD

**Issue by Dyrnwyrm** [Moerill/token-mold#163]
If you have Token Variant Art installed and Token Mold it causes an issue where selecting a "Default Wildcard Image" doesnt apply to the token even if is linked.

Just install both mods, go to Prototype Token, Set the fields as intended (Path to image, etc) now set "Randomize Wildcard Image" and go to the configuration below "Wildcard Drop Default"

If it was not bugged the image should be the "Wildcard Drop Default"  set on the token configuration but it picks a random one from the selected folder everytime you create the token on the scene, i set the options of Token Mold to only work on Unlinked Actors and all my Player Characters are Linked Actors

**Module incompatibilities**
Token Variant Art

 - DnD5E Latest Version
 - FVTT Version Latest
 - Module version Latest

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
