### ISSUE TITLE
[BUG] Character sheets not shown anymore when installing Token Mold

### ISSUE THREAD

**Issue by weiserwolf** [Moerill/token-mold#165]
Hi there, I use FoundryVTT with Pathfinder 2e installed and with Spanish Language installed. When I installed Token Mold, Character sheets are not shown correctly anymore. When I uninstall Token Mold, everything is corrected and caracter sheets are fine again.

Here you can see the monster sheet when the module is not enabled:

https://drive.google.com/file/d/1Vq6lg6cnm2N1JOOtjTSTAvsCbWbjYA4-/view?usp=share_link

Here you can see the monster sheet when the module is enabled:

https://drive.google.com/file/d/1Pt5EvCW0RnK0m-dJYRnd0KwHVFcVkERy/view?usp=sharing

Those are the available sheets and both show the same thing when enabled:

https://drive.google.com/file/d/13cXc_KntMo4vYpXfHREh7K4bn7orrmkc/view?usp=sharing

Other monsters just show a blank sheet as you can see here:

https://drive.google.com/file/d/1L9qI24P422sn3qh_Tns4niCgA4Z0XSH9/view?usp=sharing

**To Reproduce**
1. Double left click on token
2. wrong character sheet or format shown

**Expected behavior**
1. A character sheet or monster sheet with all the stats and correctly formated

**Desktop (please complete the following information):**
 - OS: Windows 10 64 Bits
 - Browser Chrome
 - FVTT Version 10 Build 291
 - Module version 2.15.4

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
