### ISSUE TITLE
HP roll always sends message to public chat and is sometimes triggered twice

### ISSUE THREAD

**Issue by espositos** [Moerill/token-mold#17]
At the moment (DND5e 0.92, FoundryVTT 0.6.1) I have some strange behaviour with the HP roll for a token always being sent to public chat, regardless of what settings I have used. In fact, when I ask for it to be sent to chat it is still sent to chat and a separate roll is sent to me privately as GM.
![hp_roll_behaviour](https://user-images.githubusercontent.com/14127543/83562303-a0dfac00-a519-11ea-848d-3ab37c6ecded.gif)

Sorry, and the missing information:
**Token Mold version**: 2.6.1.
**FVTT version:** 0.6.1 (& DND5e 0.92)
Firefox Browser 76.0.1 and Windows 10.
**Bug description**
**What happened?** The HP roll is always sent to chat. Additionally, if 'send to chat' is checked, two rolls are made: one to chat and one to the GM.
**What should've happened?** The HP roll should only be sent to chat when 'send to chat' is checked. And if it is sent to chat, then a separate roll shouldn't also be sent to the GM.
**Console errors?** None.
**Workflow to recreate the bug:** Uncheck 'send to chat' and then drag actor onto scene. Or uncheck 'send to chat' and then drag actor onto scene.

**Comment by Moerill** [comment]
of course its rolling publicly! You've selected roll mode "Public Roll" selected. But you're not the first person stumbling over this.. 

But thanks for the very nice and detailed bug report!

**Comment by Moerill** [comment]
oh wait i ignored the triggered twice thing when reading this!
reopening and checking it for next update

**Comment by Moerill** [comment]
iirc i talked with someoneabout exactly the same bug
was triggered by CUB rolling HP as well.
