### ISSUE TITLE
[Feature] Token Mold Update!

### ISSUE THREAD

**Issue by Geekswordsman** [Moerill/token-mold#170]
Hey everyone :)  

I wanted to say thank you for continuing to report issues with Token Mold here and for the kind words about the module.  Moerill definitely kicked butt when he first made it, and I've done my best as maintainer since they had to step away to keep the module going, fix bugs and tweak the features.

I do want you all to know I'm still working to update TokenMold; v3 is being a complete rewrite from the ground up to solely support v11 and onward however irl has really kicked me and made it harder for me to continue working on it on any kind of regular schedule.  Still poking at it though :)

What is going to all be in v3?  Well... just have to wait and see :D  

However, I know this doesn't help with Foundry v11 being stable _now_ and TokenMold not being compatible.  I was really trying to not do an incremental update prior to v3, but with how things have been, I think I'll need to put v3 on hold and get an interim 2.5 version out to keep us going.

Thanks again for all your support, and I promise I'll try and get that interim patch out as soon as I can!

**Comment by JayDGee** [comment]
Wonderful. Thank you.

**Comment by Doresain** [comment]
Thanks so much for putting in the effort to maintain this @Geekswordsman , and doubly so for investing the effort in a rewrite. Looking forward to it if and when IRL lets up on you :)

**Comment by terrysidhu** [comment]
Hooray!  Thank you!

**Comment by knro** [comment]
Keep up the wonderful work!

**Comment by Conandy1970** [comment]
I have no idea if you have room for requests, but I'd love to see the ability to specifiy a "% of Maximum" hit points as tokens are dragged onto the field.  Right now we have "HP per the actor data" and "roll the dice".  I'd love to see a "% of maximum per the dice roll formula" option.   Even better if it is a pop up that happens as you drag the token onto the map.

**Comment by asherett** [comment]
Hoping there's still progress on a v3 of Token Mold? Right now the most pressing issue is probably #197, which really reduces module function in current dnd5e.
