### ISSUE TITLE
[BUG] Stat Overlay Icons are mostly broken

### ISSUE THREAD

**Issue by nschoenwald** [Moerill/token-mold#172]
**Using the template**  
I'm using V11 and the current dnd5e system. I updated the module to the latest version. I am using chrome browser.

<img width="543" alt="image" src="https://github.com/Moerill/token-mold/assets/72390280/51cc21ff-e800-4a97-ace2-cd8849951425">

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
