### ISSUE TITLE
v11 Warning - Dependencies -> Relationships

### ISSUE THREAD

**Issue by rafacrudi** [Moerill/token-mold#175]
Thank you so much for making this work on v11, love this module!

I'm getting a warning saying:
The module "token-mold" contains "dependencies" which is deprecated in favor of "relationships.requires"

I can see a 
  "dependencies": [],
under module.json file. I believe just changing it to:
  "relationships": [],
will fix the warning. Worked for me. Didn't try removing it, but should work the same way since it's empty.

Cheers!

**Comment by Geekswordsman** [comment]
This is due to backwards compatibility requirements for v9.  It will be fixed in v3 :)
