### ISSUE TITLE
[BUG] No longer functional in 10.303 and DND5e 2.2.2

### ISSUE THREAD

**Issue by jopeek** [Moerill/token-mold#178]
**Describe the bug**
Dragging tokens onto a scene no longer applies name, HP, config, or overlay changes. It's essentially non-functional.

There seems to be a conflict with some other mod. In a clean world, this works fine. 

Console error:

![image](https://github.com/Moerill/token-mold/assets/1186554/c4516802-2f15-4f7f-93f8-f3af37000bac)

**To Reproduce**
1. Drag token to scene

**Expected behavior**
See token altered as per configuration.

**Screenshots/GIFs/Videos**
![image](https://github.com/Moerill/token-mold/assets/1186554/c4516802-2f15-4f7f-93f8-f3af37000bac)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - FVTT Version 10.303
 - Module version latest

**Additional context**

**Comment by dczwardCZAR** [comment]
I am having the same sort of error/issue...

when dragging an unlinked token onto the scene, nothing happens, and the console sows this error...

#################################

foundry.js:753 TypeError: Error thrown in hooked function '' for hook 'preCreateToken'. Cannot set properties of undefined (setting 'attribute')
[Detected 1 package: token-mold]
    at TokenMold._overwriteConfig (token-mold.js:364:29)
    at TokenMold._setTokenData (token-mold.js:331:36)
    at Object.fn (token-mold.js:288:28)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at #preCreateDocumentArray (foundry.js:13508:44)
    at async ClientDatabaseBackend._createDocuments (foundry.js:13394:22)
onError @ foundry.js:753

#################################

- DnD5e
- FVTT V 10.305
- Mod version latest
- macOS

**Comment by Geekswordsman** [comment]
re: @dczwardCZAR  - I'm unable to reproduce this.  Try clearing your cache (ctrl-f5) or uninstalling/reinstalling Token Mold.  If this does not resolve it, I would create a new issue here for us to track as the issue is separate from this one.

re: @jopeek From the error, it looks like DFred's Droppables, but I'm not able to reproduce this when I enable that module.  I recommend the same initial steps as above (cache clear and if that fails, reinstall of Token Mold).  If it still does not work, then use the Find the Culprit module so we can narrow down what combination might be causing this.

**Comment by dczwardCZAR** [comment]
I just reproduced this. I cleared cache, uninstalled/reinstalled token mold. This happens in Chrome, Firefox. I used find the Culprit, with this result...

<img width="406" alt="Screenshot 2023-07-09 at 2 44 05 PM" src="https://github.com/Moerill/token-mold/assets/91574640/a0fe4d88-0963-4f2c-9572-ddc4fa0b42b9">

**Comment by jopeek** [comment]
I’ve reinstalled TokenMold and still get that error in my world even if it is the only module enabled. Which matches with the other report from Culprit.

However, in a different world which I use to test my own mods, it works fine. So there seems to be something in this particular world that’s causing the issue. Strange though because it used to work fine. I will place blame at the dnd5e system update….. unfortunately that just means the mod is unusable in this world for me now. Shame.

**Comment by jopeek** [comment]
Yes that’s it. Turning off the Config option makes it work again. In fact the 2nd bar setting of None caused the issue. Unchecking that resolved it. Changing to a bar other than None also worked.

**Comment by dczwardCZAR** [comment]
Yes, I can confirm unchecking the 2nd bar setting fixed the issue for me as well.

**Comment by Kerdude** [comment]
Seeing this as well in the Pathfinder 2e system (4.12.9), Foundry version 10.303. I don't have the 2nd bar config checked but turning off config entirely makes it work again for naming tokens.

![image](https://github.com/Moerill/token-mold/assets/77137657/82b3381d-d69c-4e22-ac45-dbe1f7da7271)
