### ISSUE TITLE
[BUG] In v11, override vision to enabled does not work

### ISSUE THREAD

**Issue by Zamrod** [Moerill/token-mold#179]
If you check override for the Vision Enabled feature then drag a token to the canvas that does not have vision enabled it will not be enabled.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - FVTT Version 11.305
 - Module version 2.20.2

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.

**Comment by tcabanski** [comment]
This is still a problem with version 12 build 3.34.  The override vision setting does not work. Game system is dnd 4.0.4 and Token Mold version is v2.22.2.
