### ISSUE TITLE
[BUG] Throws an error with DAE

### ISSUE THREAD

**Issue by Mesk62** [Moerill/token-mold#180]
**Describe the bug**

Throwing an error with DAE's /dae/module/DAEdnd5e.js

![Screenshot 2023-07-16 142708](https://github.com/Moerill/token-mold/assets/43838083/af6ae45f-83d4-4a99-88b2-7bee648d8a62)

I'm not quite sure how it's interfering yet.. will do some more testing.  When I disable Token-Mold it goes away.   Will also talk to the folks over at Midi/DAE when I get a chance.

**To Reproduce**
install DAE & Midi
install Token-Mold
activate all the above

**Desktop (please complete the following information):**
Chrome running on Windows 11
FoundryVTT running on Ubuntu 20.04 cloud VPS
Foundry 11.305

**Additional context**
I believe this is messing with some of my DAE/Midi flags but will do more testing.. I'm not a coder (sure wish I was!) but posting here for info.  Perhaps it's a DAE issue but easier to disable tokenmold for me than DAE.

Thank you for all your work!

**Comment by BeardedGnome** [comment]
Fixed for Foundry v12 in latest version. See issue:
https://github.com/Moerill/token-mold/issues/204

**Comment by BeardedGnome** [comment]
Fixed.
