### ISSUE TITLE
[BUG] Reapply setting gives error

### ISSUE THREAD

**Issue by Fyrexian** [Moerill/token-mold#181]
**Describe the bug**
It seems that when I place tokens into the map, it applies the settings. However, when there is tokens already placed on the map before the module is enabled (or is placed on the map already because of an adventure) and I select them all to be reapplied, it gives this error. 
![image](https://github.com/Moerill/token-mold/assets/47077661/415ac6ca-0e8d-41df-b7ce-259b9af781bf)

When I remove the hp attribute that the error is talking about, it gives me this error instead.
![image](https://github.com/Moerill/token-mold/assets/47077661/069f1e44-f9d2-4e12-8fd6-14a21b5ab189)

**To Reproduce**
1. Select token
2. Click the reapply button in actors tab

**Expected behavior**
To apply the settings to the token

**Desktop (please complete the following information):**
 - FVTT Version [v11:305]
 - Module version [2.20.2]
 - PF2e [5.1.2]

**Comment by DrWiFi** [comment]
I'm getting a similar issue in the dnd5e module. 
Dragging a token onto the scene will apply the settings as normal, but attempting to re-apply (to re-roll HP or Name) throws this error:

<img width="1117" alt="Screenshot 2023-07-18 at 9 40 43 AM" src="https://github.com/Moerill/token-mold/assets/50341031/902ef719-520f-47e5-83a5-bcd706faf651">
