### ISSUE TITLE
[BUG] The module "token-mold" contains "dependencies" which is deprecated in favor of "relationships.requires"

### ISSUE THREAD

**Issue by kevinroyalty** [Moerill/token-mold#186]
**Describe the bug**
Curent version (as of today) of FoundryVTT and DnD5e game system (2.3.1) with token mold add-in.

**To Reproduce**
have all 3 above and you'll see this error.  We are using this with game world "odyssey of the dragonlords" if that helps.

**Expected behavior**
no error and the token-mold features work.

**Module incompatibilities**
none that we can see

**Desktop (please complete the following information):**
 - OS: Windows 10 22h2
 - Browser Edge Chromium (Current)
 - FVTT Version 11.308
 - Module version 2.20.3

**Comment by Fridan99** [comment]
the same issue

**Comment by DarkenedOrigins** [comment]
same issue 
```
The module "token-mold" contains "dependencies" which is deprecated in favor of "relationships.requires"
```

os: linux
browser: chrome
fvtt:  11.309
mod ver: 2.20.3

**Comment by kevinroyalty** [comment]
Still getting this error with latest download of FoundryVTT and this module.

**Comment by KPMcDonell** [comment]
os: Win11
browser: chrome
fvtt: 11.313
mod ver: 2.20.3

**Comment by denisbrandao** [comment]
On module.json just change
  "system": [],
  "dependencies": [],
to 
relationships: {
    systems: []
}
And it is solved.
