### ISSUE TITLE
[BUG] TypeError: Cannot set properties of undefined (setting 'attribute')

### ISSUE THREAD

**Issue by spookymonster** [Moerill/token-mold#187]
**Describe the bug**
Using Pathfinder 2E world, which does have a 'mystify NPC' option that does something similar to NPC names. Could that be conflicting?

Clicking on the 'reapply all settings' button doesn't do anything. Console logs show the following errors:
![image](https://github.com/Moerill/token-mold/assets/16195156/f98b1017-bcb9-4b90-880b-123bbde56d56)

However, going into the settings panel and clicking 'regenerate names for selected tokens' does change the names (but nothing else), with the following errors in the console:
![image](https://github.com/Moerill/token-mold/assets/16195156/02b247f9-813f-4393-9c72-1cbcddae8554)

**To Reproduce**
See above

**Expected behavior**
Clicking the 'reapply all settings' button should apply the name and overwrite the display settings for resource bars.

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Edge
 - FVTT Version: 11.308
 - Module version: 2.20.3

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
