### ISSUE TITLE
[BUG] Token Mold Name Override Prevents Token Variant Art Randomiser / Popups from working

### ISSUE THREAD

**Issue by schmickers** [Moerill/token-mold#188]
When the modules Token Mold and Token Variant art are active, the token image randomizer and image select pop ups from Token Variant Art do not occur. 

Disabling the Name setting in the Token Mold header restores this functionality. 

**To Reproduce**
1. Install Token Mold
2. Install token Variant Art
3. Create a token
4. Token image is not randomised by TVA

**Expected behavior**
Token Mold should make its changes to the token name and allow TVA to randomise the image / display an art select pop-up. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Foundry Virtual Tabletop: Version 11 Stable, 11.308
 - Game System: dnd5e, 2.3.1
 - token Mold 2.20.3
 - Token Variant Art 4.56.1

**Comment by chrisjbrown** [comment]
Same issue. Not sure if there is a way to allow TVA to go first in updating the image before the name is changed. Or could TVA use a different field than token name to choose it's image variant

**Comment by chrisjbrown** [comment]
Notified TVA creator but they say that this needs to be resolved in token mold
https://github.com/Aedif/TokenVariants/issues/152#issue-2204274391

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
