### ISSUE TITLE
[BUG] Savage Worlds, Stat Overlay, No Attributes

### ISSUE THREAD

**Issue by paladintodd** [Moerill/token-mold#190]
**Describe the bug**
In a Savage Worlds Adventure Edition, there are no attributes available other than Name in the Stat Overlay. 

No errors in console when opening the Token Mold options. 

**To Reproduce**
1. Go to Actors tab
2. Click on Gear for Token Mold
3. Click on Stat Overlay
4. The Attribute dropdown will have only None and Name

**Expected behavior**
Should be some attributes here. 

**Module incompatibilities**
Reproduced with no other modules active

**Screenshots/GIFs/Videos**
![image](https://github.com/Moerill/token-mold/assets/15892269/bad64c85-aaee-43c9-ae1c-37a4ea1eb4ea)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [Chromes]
 - FVTT Version [11.308]
 - Module version [2.20.3]

**Comment by JasonSunday** [comment]
I am having the same issue.

**Comment by pensan** [comment]
Also having the problem, but in a D&D 5e world.

Foundry: 11.315
Module Version: 2.20.3

**Comment by BeardedGnome** [comment]
I've published an unofficial fork that should fix the issue, please test the version that matches your Foundry install.

Foundry v11:  `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.21.0/module.json`
Foundry v12:  `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`

**Comment by BeardedGnome** [comment]
Latest version for v12 will be posted in this issue:
https://github.com/Moerill/token-mold/issues/204

**Comment by BeardedGnome** [comment]
Fixed.
