### ISSUE TITLE
Help interpreting a Token Mold console error 

### ISSUE THREAD

**Issue by rtschaefer** [Moerill/token-mold#193]
<img width="743" alt="Monitor Flash Bug" src="https://github.com/Moerill/token-mold/assets/95512317/96c81bd8-f739-4392-86a6-73b39275bfca">

I am learning how to better understand and interpret console errors.  Could this be a conflict between TM and Drag Ruler??   

My issue is not resolved by simply turning modules on or off or using FTC, because the bug is random in occurrence and might take an hour to replicate. When editing a token/character sheet, the monitor will flash black for a second and then resolve. However, when it resolves, all token vision is broken, and the scene goes black when any token is selected. A browser refresh fixes the issue.... until of course, 5 or 6 or 27 token edits later, when it happens again. 

Any intel or ideas would be most appreciated. I have done just about every WebGL, Graphic Driver update, and Chrome Browser setting checks imaginable, so I highly suspect a module conflict, but cannot use the "turn off all modules" approach without taking a week's vacation to wait up to an hour to test each and every iteration. 

Thanks for reading my rambling.

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
