### ISSUE TITLE
[BUG] Token Bar overwrite does not work for Forbidden Lands system

### ISSUE THREAD

**Issue by r-valyar** [Moerill/token-mold#194]
**Describe the bug**
When I am trying to configure overwrite for Display Bars, Bar 1 Attribute and Bar 2 Attribute for unlinked tokens in Forbidden Lands system, it does not work. Name overwrite works for example, but bars do not. 

**To Reproduce**
1. Install Forbidden Lands system
2. Enable Token Mold and configure settings according to the screenshot
3. Drag & drop token - the bars are not displayed

![image](https://github.com/Moerill/token-mold/assets/63558984/9d70c11b-54e6-4a0b-8f4a-75e0eeaa3ddb)

**Expected behavior**
Attribute Bar 1 should be visible as per the configuration when token is dragged & dropped to the scene

**Module incompatibilities**
I tested this on clean world with just system and this module enabled. Can't identify other module 

**Screenshots/GIFs/Videos**
The screenshot is attached above.

**Desktop (please complete the following information):**
 - OS: Windows/MacOS
 - Browser: Firefox 121; MS Edge 120
 - FVTT Version: 11.315
 - Module version: 2.20.3
 - System: Forbidden Lands 11.4.1

**Additional context**
n/a

**Comment by JonLark** [comment]
Same bug in Pathfinder 2e. Will not override. In fact, when you try to override the display bars, it removes the appended naming as well.

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
