### ISSUE TITLE
[BUG] Gear wheel is not bringing up Token Mold Icons

### ISSUE THREAD

**Issue by OnegoodgreekDM** [Moerill/token-mold#202]
Hi there thanks so much for taking the time to help.
I wanted to change some of the settings in Token Mold and I have attempted to access the settings through the gear wheel on the Actors tab: 
<img width="305" alt="image" src="https://github.com/Moerill/token-mold/assets/68712391/5e066eb6-754e-4bb6-9f9e-211fb63374a7">

Whenever I click on it nothing happens. No pop up, no message, nothing. I recently started using this mod and I wanted to create custom names for my enemy actors. It seems to work fine in the background with the prepended descriptors appearing when I drag enemies onto the scene. 

**Describe the bug**
Here are the  console errors (F12 for most browsers) that occur.
<img width="251" alt="image" src="https://github.com/Moerill/token-mold/assets/68712391/14e5a12e-69be-480e-8a88-f46bdcb698f9">

**To Reproduce**
1. Go to 'Actor's Panell'
2. Click on 'Gear Wheel'
3. Nothing Appears
4. No Error

**Expected behavior**
Open the settings for token mold.

**Module incompatibilities**
Please try to reproduce your bug with all other modules deactivated. If this module clashes with another module, please find that module and report it here.  
The [find the culprit](https://github.com/Moerill/fvtt-find-the-culprit/) module may prove to be useful here.

**Screenshots/GIFs/Videos**

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - FVTT - Forge V11 stable Patch 13 build 315
 

**Additional context**

**Comment by OnegoodgreekDM** [comment]
<img width="251" alt="Screenshot 2024-03-25 at 8 34 06 PM" src="https://github.com/Moerill/token-mold/assets/68712391/06530d9d-53f3-4bb1-926b-6115e2bf08c9">
<img width="251" alt="Screenshot 2024-03-25 at 8 34 13 PM" src="https://github.com/Moerill/token-mold/assets/68712391/287eafbe-9154-417f-bf0b-8d7b42172fee">
<img width="251" alt="Screenshot 2024-03-25 at 8 34 18 PM" src="https://github.com/Moerill/token-mold/assets/68712391/ca4802eb-5173-4ae4-acca-59f158125e9f">
<img width="251" alt="Screenshot 2024-03-25 at 8 34 21 PM" src="https://github.com/Moerill/token-mold/assets/68712391/28638976-a54d-435c-a159-fb53c7d98089">

Here are further screen shots

**Comment by Lector** [comment]
i am having the same issue.

**Comment by Omeged** [comment]
I am getting the same error in MS Edge
![image](https://github.com/Moerill/token-mold/assets/71626248/5cea93ec-e86d-45ad-86ca-a0182f1b7b03)

**Comment by Beta-Max** [comment]
I'm still having this issue, (can't access token mold settings at all)  and I'm a bit new to github, do we have a solution for this?

**Comment by aydeaver** [comment]
Here as well.

**Comment by Mattrogers13** [comment]
came here to report the same issue

**Comment by BeardedGnome** [comment]
Can you test my unofficial fork:
`https://raw.githubusercontent.com/BeardedGnome/token-mold/master/module.json`

**Comment by Mattrogers13** [comment]
> Can you test my unofficial fork: `https://raw.githubusercontent.com/BeardedGnome/token-mold/master/module.json`

That worked for me. I installed it and was able to access the settings.

**Comment by jseaz73** [comment]
Thank you, thank you, thank you ...
This fork worked!

**Comment by BeardedGnome** [comment]
I've published an unofficial fork that should fix the issue, please test the version that matches your Foundry install.

Foundry v11:  `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.21.0/module.json`
Foundry v12:  `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`

**Comment by BeardedGnome** [comment]
Latest release for Foundry v12 is listed in issue:
https://github.com/Moerill/token-mold/issues/204
