### ISSUE TITLE
[BUG] Issue Opening PlayerActor Sheets when Token Mold is enabled

### ISSUE THREAD

**Issue by KellethDregar** [Moerill/token-mold#206]
**Describe the bug**
When trying to open a player actor sheet nothing happens and the console log seems to throw errors pointing to the character details being missing. This only started happening after upgrading to Dnd5e System version 3.1 and after.

An error occurred while rendering ActorSheet5eChar…artial dnd5e.character-details could not be found'

**To Reproduce**
1. Enable the Token Mold Module
2. Attempt opening an Actor Sheet

**Expected behavior**
The actor sheet opens displaying the 

**Module incompatibilities**
Attempting to troubleshoot with Find the Culprit and token mold active it seems to point to multiple modules being the issue but when disabling those the issue seems to continue occurring. 

**Screenshots/GIFs/Videos**
![image](https://github.com/Moerill/token-mold/assets/79947702/03a28134-5eb1-4d45-978e-5ce1b01fe662)

**Desktop (please complete the following information):**
 - Hosted on Forge VTT
 - FVTT Version: 11.315
 - Module version: 2.20.3

**Comment by BeardedGnome** [comment]
I've published an unofficial fork that should fix the issue, please test the version that matches your Foundry install.

Foundry v11:  `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.21.0/module.json`
Foundry v12:  `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`

**Comment by KellethDregar** [comment]
Will test it out more this weekend to see if I can find any other issues with the sheets. But from my initial testing it seems to be working without problems! Appreciate the quick fix!

**Comment by KellethDregar** [comment]
I was able to test more thoroughly and didn't encounter the old issue at all, thank you again for the fix!
