### ISSUE TITLE
[BUG] Pathfinder 1e, does not show all attributes in overlay.

### ISSUE THREAD

**Issue by Wedge94** [Moerill/token-mold#208]
Stat Overlay does not show all attributes, only some randomly selected ones.

For example, I want to choose AC total, but I can only take AC abilty, not total. With many things it is like that. Total random options for me.

![obraz](https://github.com/user-attachments/assets/44e3cd6d-e6a9-48ac-b392-1ce964ab579a)
![obraz](https://github.com/user-attachments/assets/66119d9a-dd01-45c6-9c6c-19d3c9ae15a2)

Tested without any other modules.

Foundry V11 315
Pathfinder 1e 10.4
Token Mold 2.20.3

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
