### ISSUE TITLE
[BUG] Cannot disable Stat Overlay

### ISSUE THREAD

**Issue by jopeek** [Moerill/token-mold#210]
**Describe the bug**
There appears to be no way to NOT have the stat overlay appear on tokens. There is no way to remove all the attributes. I can add a new one, leave it blank, and remove the existing two, but upon a reload, that will be reverted. 

It doesn't seem to be possible not to have a stat overlay at all

**Expected behavior**
Allow me to remove all stat overlay attributes and not see any.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Latest Edge
 - FVTT Version 12.331
 - Module version 2.22.2

**Comment by BeardedGnome** [comment]
This doesn't work?
![image](https://github.com/user-attachments/assets/11685e1a-e6a1-4ec5-834c-fe70bbc097bb)

**Comment by jopeek** [comment]
Well.... don't I feel like an idiot ;) Yes, it does work.
