### ISSUE TITLE
[BUG] Override vision setting is not working for tokens dropped on map

### ISSUE THREAD

**Issue by tcabanski** [Moerill/token-mold#214]
**Describe the bug**
Override vision setting is not working.

There are no errors in the console.

**To Reproduce**
1. Change your settings to modify default config by checking both overwrite and vision enabled in the vision section
2. Drop a new NPC token that does not have vision set.  It will not be modified.

**Expected behavior**
I expected the vision setting to be turned on for the token on the map

**Desktop (please complete the following information):**
 - OS: Windows 12
 - Browser Edge
 - FVTT Version 12 build 331
 - Module version 2.22.2

**Comment by tcabanski** [comment]
I also tested in a clean world with only one module enabled: Token Mold.  The vision does not get set.

Everything else I use with token mold appears to be working.  For example, token naming and display bar overrides.

**Comment by BeardedGnome** [comment]
Thank you for the update. Crazy busy, but I'll look at when I get some free time.

**Comment by davidR1974** [comment]
token vision enabled property ('has Vision' checkbox) in newest version of dnd5 system may have changed, moving from 'vision' to  'sight.enabled' property..

Changed line 408 in token_mold.js from 

`data[key] = value.value`
to
`data[(key == 'vision' && game.system.id == 'dnd5e' ) ? 'sight.enabled' : key] = value.value;`

but maybe there's a better way to do it..

**Comment by BeardedGnome** [comment]
I'm not ready to support D&D 4.x yet. But I'll keep this in mind when that time comes.

**Comment by davidR1974** [comment]
> I'm not ready to support D&D 4.x yet. But I'll keep this in mind when that time comes.

Well in that case i have to say it is working surprisingly well for an unsupported system.. Good job.

**Comment by BeardedGnome** [comment]
Looks like `sight.enabled` is part of the old D&D5e 3.x. I'll see about getting that fixed.
