### ISSUE TITLE
TokenMold setting token scale value to 1 for linked tokens

### ISSUE THREAD

**Issue by adacosta92** [Moerill/token-mold#23]
The prototype tokens for some characters have a scale value at 1.3 (warforged barb) or 0.6 (female elf sorc), but when I drag them on to the canvas, their scale value is set to 1. This only happens when tokenmold is activated, and even deactivating the "config" option doesn't fix it

FVTT 0.6.2
D&D 5E 0.93
TokenMold 2.6.1

**Comment by cojoMan** [comment]
adding to this. I have a horse token I want to have scaled to h/w=1/2 instead of 1x1. So I set it as so in the protoype token, then disable ALL the toggles for token mold, and it comes in at 1x1. If I go in and specifically disable the scale, it comes in fine. I would have assumed toggle disabling should have worked too ? Isn't this one of the toggles ?

**Comment by Moerill** [comment]
90% sure its the setting shown in the screenshot that is the error:
![image](https://user-images.githubusercontent.com/26152015/85799642-d9049400-b73f-11ea-8e34-fecae377e98c.png)

i'm not making it obvious enough that this is independent of all the quick toggles..

**Comment by cojoMan** [comment]
Yes, that is the setting that fixed it, it's on me for assuming this was linked to one of the toggles. 
If there could be a label at the bottom of each section(tab) that is NOT linked to toggles stating that, it would go a long way.
And thank you so much for this module, I should have lead with that :)

**Comment by adacosta92** [comment]
So should I turn that setting off when placing linked tokens? Is it possible for two settings to set token size scaled to map, one for linked and one for unlinked?

also, YES THANK YOU THIS MODULE IS AMAZING! <3

**Comment by Moerill** [comment]
@adacosta92 thanks :blush: those kind of words help to encourage creating stuff!

if you set the "apply settings to unlinked tokens only" s etting nothing should be applied to linked tokens.
If it  still does.. i would need a more elaborate bug report with  examples.
