### ISSUE TITLE
Bug: Set Token Size to Creature Size Doesn't Respect Unlinked Actors Only Setting

### ISSUE THREAD

**Issue by Dumbhuman** [Moerill/token-mold#28]
![image](https://user-images.githubusercontent.com/63615591/86998828-0dc41280-c166-11ea-8bd6-184c542ca5c7.png)

At least I think this is a bug.  In Foundry 6.5 with DND 5e 0.93, I expected the checkbox at the top to prevent the token size setting checked at the bottom from taking place on unlinked tokens, but dropping in a Small creature with its Prototype token linked to the actor and scale set to 1.1 still resulted in that token being set to a 0.8 scale when dropped on the canvas.

**Comment by Moerill** [comment]
I put this on purpose before the check.. 
Don't know why though :sweat_smile: 
Only guess it was before i added that setting for unlinked tokens....

anyway fixed now
