### ISSUE TITLE
TypeError when deleting any token in 0.5.6 Hotfix#1

### ISSUE THREAD

**Issue by Norc** [Moerill/token-mold#3]
When I delete any token, I get the following error in the console (but the token does delete). Happens with both linked and unlinked tokens:
![image](https://user-images.githubusercontent.com/64667579/81933551-9c2f7400-95bb-11ea-8f6a-7db651216084.png).
**Test info**:  0.5.6 hotfix#1, only TokenMold 2.6.0 active. Let me know if you want more settings info.

**Comment by Norc** [comment]
Was found in 0.5.6 Hotfix #1, confirmed it is still unchanged in 0.5.7.

**Comment by Moerill** [comment]
Can't really reproduce, checked the line and added an extra check to try to avoid  this issue.
Hope this fixes it!
