### ISSUE TITLE
Movement shown is max, not current. Should be current.

### ISSUE THREAD

**Issue by geoidesic** [Moerill/token-mold#44]
Variant encumbrance may alter movement speed: https://github.com/VanirDev/VariantEncumbrance

It would be good if this could be reflected accurately.

**Comment by Moerill** [comment]
This will probably not happen, at least as long as the module you linked above doesn't store its data somewhere in the actors data model.

**Comment by Moerill** [comment]
If the state of the problem does change (e.g. the module above does starting to store its value somewhere) just comment under this issue and i'll reopen and reconsider it.
