### ISSUE TITLE
Error with 0.5.7

### ISSUE THREAD

**Issue by DarKDinDoN** [Moerill/token-mold#5]
Hello,

Just updated to 0.5.7. On game startup I get this error:
![image](https://user-images.githubusercontent.com/1687854/82128249-f9911400-97b9-11ea-845d-c7175c9b9446.png)

**Comment by Moerill** [comment]
Are you very sure you're on the newest Token-Mold version? (2.6.0)
cause i really really hoped to have fixed this... (after 2.6 me  and it seems no one else encountered it anymore)

**Comment by DarKDinDoN** [comment]
Yes

I run FoundryVTT as admin:

![image](https://user-images.githubusercontent.com/1687854/82128591-92289380-97bc-11ea-9029-5d22b34859f5.png)

**Comment by Moerill** [comment]
!)("Z$§Z!")($Z 

does it keep happening, even after reload?
does randomizing adjectives work for you?

**Comment by DarKDinDoN** [comment]
Happens when I launch FVTT and the first time I enter the campaign.
Reloading the page while in game doesn't show the error message.

**Comment by Moerill** [comment]
ok thanks
so its still the same error .. meh
i'll see what i can do, but i'm not really optimistic here - but in the end its good that it doesn't really affect the usage.

**Comment by DarKDinDoN** [comment]
Ok that's weird. No more issue.
Might be a conflict with another package.
Sorry for the trouble!
