### ISSUE TITLE
[FEATURE]Adding a reduced set of Adjectives(English)

### ISSUE THREAD

**Issue by buttonpushertv** [Moerill/token-mold#54]
Based on this [Reddit post](https://www.reddit.com/r/FoundryVTT/comments/it0b77/list_of_571_adjectives_for_token_mold/), there is a desire out there for a reduced set of Adjectives to use for TokenMold. I thought I'd offer up the listing that [u/VagabondVivant](https://www.reddit.com/user/VagabondVivant) offered for inclusion in the next update to TokenMold. The listing can be found, in text form, [here](https://textbin.net/fADrn8mGtE).

I've attached their 571 word listing as a FVTT pack db to make things easy to import if you'd consider it. I zipped it so that I could attach it here.

[adjectivesreduced.zip](https://github.com/Moerill/token-mold/files/5226749/adjectivesreduced.zip)

Thanks (still love your work!).

**Comment by focalmatter** [comment]
Updated the list (removed some words that didn't really work, added a few new ones: **https://textbin.net/AzIA7sUopE**

**Comment by Moerill** [comment]
i'm fine with adding them and possibly even as default (cause its a more curated list).
though i'll wait a bit until you're all settled on one set of adjectives :sweat_smile:

**Comment by buttonpushertv** [comment]
Please consider retaining the larger database as an option though. Thanks.

**Comment by focalmatter** [comment]
> i'm fine with adding them and possibly even as default (cause its a more curated list).
> though i'll wait a bit until you're all settled on one set of adjectives 😅

I _thought_ I was done (I had only edited it once I realized it could go into the mod), but now that I have the option to refine it some, my inner perfectionist wants to take one final crack at it. I'll give it one last edit tonight and update the thread when it's ready ready.  😁

**Comment by Moerill** [comment]
> Please consider retaining the larger database as an option though. Thanks.

yes ofc!
just thinking about the new one being the defaullt (for new users)

**Comment by focalmatter** [comment]
Okay **[it's done](https://textbin.net/A9EcD8OSL4)**. 700 words, tidied and capitalized. I'm sure it could be longer but I'm done. 700 is plenty. Enjoy!

**Comment by Moerill** [comment]
Thanks for your work!
List was added with Token Mold 2.9
