### ISSUE TITLE
[BUG] Add adjective bugged — doesn't work, resets all other settings

### ISSUE THREAD

**Issue by focalmatter** [Moerill/token-mold#55]
So in an ironic twist of fate, after spending all that time putting together an improved adjective list, I go to install it and ... the module is bugged.

First off I should mention that this bug only occurs in one of two worlds using the module. The other world has zero issues with it.

However the bugged version basically won't let me place adjectives in front of the name. If I try to turn on the setting, _all_ the token settings get overridden and new tokens show up totally stock. If I disable the adjective flag, it goes back to creating tokens with all the custom settings I had set.

I don't think it's a module incompatibility issue, as both worlds use the same modules, but only one is bugged. It should be noted that it's bugged even with the stock adjective dictionary and not a custom one.

Is there a way to fully reset the module? I tried uninstalling and reinstalling, but when I did the settings were all still there.

**Comment by focalmatter** [comment]
So I just updated the module and saw the updated Adjective lists ... but still can't use them. For whatever reason the bug is still there, and so long as the "Add Adjective" toggle is turned on, the token shows up totally default.

It's only the one game that's bugged. It doesn't happen in any of my other games.

**Comment by Moerill** [comment]
So i am not sure i understand the issue.
All but one world: everything is fine.
Other world: settings are broken for you?
Have you checked the console for errors?
What does the console say regarding the saved settings for token mold, when you do change smth in your settings? (Talking about an entry like this: 
![image](https://user-images.githubusercontent.com/26152015/94030504-2e435680-fdbe-11ea-83cd-0969c2cb676f.png) )
try uncollapsing that as far as possible and send me a screenshot, together with your settings in the settings screen.

**Comment by focalmatter** [comment]
Thanks for suggesting that. I've never troubleshooted modules before, didn't think to check Console. 

Here's what came up:

```
token-mold.js:751 Uncaught (in promise) TypeError: Cannot read property 'uuid' of null
    at TokenMold.saveSettings (token-mold.js:751)
    at TokenMoldForm._updateObject (token-mold.js:887)
    at TokenMoldForm._onSubmit (foundry.js:4761)
    at TokenMoldForm._onSubmit (token-mold.js:855)
    at TokenMoldForm._onChangeInput (foundry.js:4796)
    at HTMLFormElement.dispatch (jquery.min.js:2)
    at HTMLFormElement.v.handle (jquery.min.js:2)
saveSettings @ token-mold.js:751
_updateObject @ token-mold.js:887
_onSubmit @ foundry.js:4761
_onSubmit @ token-mold.js:855
_onChangeInput @ foundry.js:4796
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2


token-mold.js:751 Uncaught (in promise) TypeError: Cannot read property 'uuid' of null
    at TokenMold.saveSettings (token-mold.js:751)
    at TokenMoldForm._updateObject (token-mold.js:887)
    at TokenMoldForm._onSubmit (foundry.js:4761)
    at TokenMoldForm._onSubmit (token-mold.js:855)
    at TokenMoldForm.submit (foundry.js:5004)
    at TokenMoldForm.close (foundry.js:4976)
    at Object.onclick (foundry.js:4172)
    at HTMLAnchorElement.<anonymous> (foundry.js:4082)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)
saveSettings @ token-mold.js:751
_updateObject @ token-mold.js:887
_onSubmit @ foundry.js:4761
_onSubmit @ token-mold.js:855
submit @ foundry.js:5004
close @ foundry.js:4976
onclick @ foundry.js:4172
(anonymous) @ foundry.js:4082
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

**Comment by focalmatter** [comment]
Any thoughts? What's the "uuid" property it can't read?

**Comment by Moerill** [comment]
Oh sorry, missed your last comment.

ooooh i think i know whats broken
For some reason the module saved a not working or existing rollable table for you as adjective list, which seems to break everything. Which is ofc not supposed to happen!
I'll push a quick fix out.

**Comment by Moerill** [comment]
Update is pushed, please report back and possibly reopen this issue if its still a problem.
