### ISSUE TITLE
[BUG] High RAM Usage?

### ISSUE THREAD

**Issue by Mist-Hunter** [Moerill/token-mold#56]
**Describe the bug**
Also post console errors (F12 for most browsers) here that occur.

When measuring performance via Chrome's task manager, most addons add 1-2MB of RAM usage to the Foundry Tab. Turning on Token Mold adds over 100MB RAM. Perhaps this expected behavior due to language lists being loaded into memory, but I'm filling just in-case it's unexpected. 

~~It is also having a modest impact on players tabs if I'm looking at things correctly.~~ I'm leaving the screen shots below, but client impacts are inconclusive so you can probably ignore that part. 

Also. Thanks for the awesome module! I use it all the time and it really helps as a DM. 100MB is totally worth the functionality to me, like I said just noticed it used allot more than my other modules.

**To Reproduce**

**Expected behavior**

Less RAM usage?

**Module incompatibilities**
Please try to reproduce your bug with all other modules deactivated. If this module clashes with another module, please find that module and report it here.  
The [find the culprit](https://github.com/Moerill/fvtt-find-the-culprit/) module may prove to be useful here.

**Screenshots/GIFs/Videos**
> A picture is worth a thousand words.

_DM Tab W/O Token Mold_
![image](https://user-images.githubusercontent.com/6420684/93717290-b4933a80-fb29-11ea-8a1a-6629d0911502.png)
_Player Tab W/O Token Mold_
![image](https://user-images.githubusercontent.com/6420684/93717527-3c2d7900-fb2b-11ea-8af7-5b9287c54851.png)
**the following add-ons are on with the pic above:**
encounter-builder--v0.2.1;
about-time--v0.1.52;
background-volume--v1.1.1;
BatchPermissionsByFolder--v0.0.2;
better-rolltables--v1.5.1;
chat-images--v1.1.3;
ChatPortrait--v0.1.4;
combat-template-cleanup--v0.1.0;
combat-utility-belt--v1.2.2;
DancingLights--v2.1.5;
deselection--v1.4.4;
dice-so-nice--v2.0.4;
dice-calculator--v0.5.10;
dynamiceffects--v0.5.101;
expander--v0.0.4;
fxmaster--v0.6.0;
scaleGrid--v0.0.12;
jitsirtc--v0.3.3;
lmrtfy--v1.2.3;
colorsettings--v2.5.0;
lootsheetnpc5e--v2.1.1;
maestro--v0.7.1;
mess--v0.11.2;
mindmap--v0.5.1;
minor-qol--v0.1.77;
mountup--v3.0.1;
npcgen--v0.1.0;
permission_viewer--v0.7;
pings--v1.2.9;
response-times--v1.0.1;
rolltable-buttons--v1.1.5;
furnace--v2.2;
tidy5e-sheet--v0.2.23;
tidy-ui_game-settings--v0.1.18;
token-health--v0.1.7;
torch--v1.0.9;
travel-pace--v0.2.1;
trigger-happy--v0.8.1;
vtta-iconizer--v2.1.12;
vtta-tokenizer--v2.2.1;

_DM Tab_
![image](https://user-images.githubusercontent.com/6420684/93717334-f45a2200-fb29-11ea-92b1-a1fc5657d36c.png)
_Player Tab_
![image](https://user-images.githubusercontent.com/6420684/93717558-6d0dae00-fb2b-11ea-90f8-635ede530246.png)
**the following add-ons are on with the pic above:**
encounter-builder--v0.2.1;
about-time--v0.1.52;
background-volume--v1.1.1;
BatchPermissionsByFolder--v0.0.2;
better-rolltables--v1.5.1;
chat-images--v1.1.3;
ChatPortrait--v0.1.4;
combat-template-cleanup--v0.1.0;
combat-utility-belt--v1.2.2;
DancingLights--v2.1.5;
deselection--v1.4.4;
dice-so-nice--v2.0.4;
dice-calculator--v0.5.10;
dynamiceffects--v0.5.101;
expander--v0.0.4;
fxmaster--v0.6.0;
scaleGrid--v0.0.12;
jitsirtc--v0.3.3;
lmrtfy--v1.2.3;
colorsettings--v2.5.0;
lootsheetnpc5e--v2.1.1;
maestro--v0.7.1;
mess--v0.11.2;
mindmap--v0.5.1;
minor-qol--v0.1.77;
mountup--v3.0.1;
npcgen--v0.1.0;
permission_viewer--v0.7;
pings--v1.2.9;
response-times--v1.0.1;
rolltable-buttons--v1.1.5;
furnace--v2.2;
tidy5e-sheet--v0.2.23;
tidy-ui_game-settings--v0.1.18;
token-health--v0.1.7;
**token-mold--v2.7.1;**
torch--v1.0.9;
travel-pace--v0.2.1;
trigger-happy--v0.8.1;
vtta-iconizer--v2.1.12;
vtta-tokenizer--v2.2.1;

**Desktop (please complete the following information):**
 - FVTT Version [e.g. 0.6.6]
 - Module version [e.g. 0.1.0]

Windows 10, 2004
Chrome Version 81.0.4044.138 (Official Build) (64-bit)
FVTT Version 0.6.6

**Additional context**

**Comment by Moerill** [comment]
100MB?!
Oh wow, did not expect that to happen! looking at the raw language files they're only about 5mb or so.

But i can replicate it and turning off the name generation feature (and reloading) does decrease memory usage drastically. (to the point that its jumping around enough so that there is not really a difference between having token mold active or not)

i'm gonna check and see if i can do smth to reduce the size, but i'm not sure if thats possible. At least i can mention it somewhere in the readme (and settings), that name generation active does increase memory usage drastically, dependend on the amount of languages used.

**Comment by Moerill** [comment]
so yeah.. the issue seems to be that javascript objects have quite the overhead <_<
I'll continue to check if there is smth to be done here, but i do not have high hopes, so a big warning is probably in place here.

**Important** The memory usage is *only* when the name generation is enabled *and* only for GMs. Players are supposed to be unaffected.

**Comment by Mist-Hunter** [comment]
Thanks for checking this. 100MB is worth it, it's a great module.
