### ISSUE TITLE
[FEATURE] Allow customization of adjectives

### ISSUE THREAD

**Issue by OverloadUT** [Moerill/token-mold#57]
**Is your feature request related to a problem? Please describe.**
I find the current (English) adjectives not very useful for generating large numbers of enemies. So many of them describe personality traits like "steadfast" and "gallant" which don't evoke much of a visual difference between them.

**Describe the solution you'd like**
I'd like to use a list of adjectives that are all visual-based to use for random unnamed enemies in a dungeon. Instead of a "gallant guard" I'd like "portly guard" and "face-scar guard" and "long hair guard"

**Describe alternatives you've considered**
I looked at editing the .db file that contains the adjectives, but it appears to be machine-generated from some source files and is very arduous to modify by hand.

Edit: I see now that this would certainly be solved by https://github.com/Moerill/token-mold/issues/53

**Comment by Moerill** [comment]
you can already use *any* rollable table as base for your adjectives. (e.g. using the easytables module or so you could just use any csv or comma separated list and easily transfer it into a rollable table)
So just create your own list as you want and you're fine.

Or did i misunderstand?

**Comment by OverloadUT** [comment]
If that's the case, then yes that's exactly what I'm looking for! Thank you!

That feature is not mentioned in the manual so I had no idea https://github.com/Moerill/token-mold#random-adjectives

**Comment by Moerill** [comment]
oooh.. i forgot to add t hat to the Readme, sorry! (not used to people actually reading them! :grimacing: )
fixing that now
