### ISSUE TITLE
[BUG] Passive Perception overlay value incorrect

### ISSUE THREAD

**Issue by mikehaart** [Moerill/token-mold#62]
![2020-09-29 21_25_12-Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application](https://user-images.githubusercontent.com/17619758/94611931-51787500-029a-11eb-9531-f6e804e94fdb.png)

New user here. I cant seem to get the correct passive perception attribute to display correctly as shown above. Overlay above should be 22 beside the eye icon but is only 13.

**Comment by glkwhr** [comment]
It's being a while but in case anyone else is also wondering, I just learned that `prc.passive` is the one for passive perception.
