### ISSUE TITLE
[BUG] Template follow option is missing since 2.10.1

### ISSUE THREAD

**Issue by gravagehulk** [Moerill/token-mold#66]
Since updating to the most recent version of the module (2.10.1) the option to have a spell template follow a token is missing. It was there in the previous version and I was using it regularly.

Foundry 0.6.6
5e version: 0.98

**Comment by Moerill** [comment]
it was intentionally removed in 2.8, see changelog:
https://github.com/Moerill/token-mold/blob/master/CHANGELOG.md#v28

**Comment by gravagehulk** [comment]
Okay, aside from the fact that I liked your implementation WAY better, I see no way to attach spell templates using that module. You can't actually select the spell template to attach it, unless I'm missing something.

**Comment by Moerill** [comment]
>  To be able to attach measure templates, lights, sounds and journals you need the select-tool-everywhere module, as of writing this there is no select tool in those controls.

from the package description.

While i'm happy that to read that you liked my implementation more, i prefer to let a module created for this specific task handle it. 
The sticky templates did never really fit into token molds concept, so i was and am happy that someone else tackled this usecase in their own module, so i could get rid of my half hearted solution.
