### ISSUE TITLE
[Spell Template Follow Token] Please add this back

### ISSUE THREAD

**Issue by gravagehulk** [Moerill/token-mold#69]
Oh man, please add the feature back that allows you to have a spell template follow the token. I hear what you're saying about it seeming out of place in the Token Mold module, but hear me out:

I've been GM'ing in Foundry since the first stable build went live. Up until you removed this feature, I was using it every week. I have two clerics in my party who consistently use Spirit Guardians and it was so nice.

I have tried using Token Attacher. Aside from the fact that it requires yet another module (Select tool everywhere) to work properly, it is incredibly clunky and frustrating to use. Your module allowed me to simply double click on the template and select one of my players from the drop down. With the other module the workflow is: Select Token > Open attaching UI > Select Measure Controls > Select Templates > drag a box around the template (especially hard for spirit guardians, which appears underneath the token in the middle of a bunch of enemies) > Attach selected element

After the spell expires or the combat is over, cleanup is even more frustrating, as I have to unattached everything. Your implementation was so much simpler and easier to use that I dread when my players cast Spirit Guardians now. Even if you just made a separate module that did nothing but that, I'd download it and install it.

Anyway, that's my rant. Thanks for all of your hard work.

**Comment by kenpoh01** [comment]
I second this.  Sticky templates was awesome for a couple of my players.

**Comment by Moerill** [comment]
Starting next week i can copy the sticky template code to a quick module (not listing on the fvtt package list), allowing for you to use it for the time being. Going onwards i'd probably still prefer to work smth out with Token Attacher.

Since you've tested it and found some  complaints about the usability, it  could be useful to add those as suggestions/feature requests to that modules github, so it may be enhanced further. (its already on a good path imo)

**Comment by Norc** [comment]
Token Auras module also might be of interest.

**Comment by gravagehulk** [comment]
Token Auras would definitely be an easier workaround than Token Attacher for the time being. Your implementation was still the simplest and best, though. It allowed me to keep my animated spell templates and have them follow the token around when it moved.

I appreciate the response.

**Comment by BeardedGnome** [comment]
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.
