### ISSUE TITLE
Reapply Settings not working in particular case

### ISSUE THREAD

**Issue by JerkyGunner** [Moerill/token-mold#7]
So the reapply settings button is a godsend for scenes I had made prior to getting Token Mold, but I'm noticing it doesn't work if in the selection of tokens there happens to be any linked actors.

If I select a scene's worth of unlinked actors then it works perfectly but if there are any linked ones among them then none of them will be updated.

**Comment by etriebe** [comment]
I'm not seeing this work in any situation.

**Comment by Moerill** [comment]
@etriebe thats because you're propably on 0.6.0

issue is fixed for next patch
