### ISSUE TITLE
Automatic token resizing not happening. 

### ISSUE THREAD

**Issue by evilcj925** [Moerill/token-mold#72]
**Describe the bug**
auto resizing of tokens when size is changed on sheet not happening
No errors in console

**Expected behavior**
token size changing to appropriate size when changed on character sheet

**Module incompatibilities**
error persisted with all other modules deactivated

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - FVTT Version 7.6
 - System 5e 1.1.1
 - Module version 2.10.1

**Additional context**

**Comment by Moerill** [comment]
works fine for me. :thinking: 
Make sure that you are editing the actors sheet, not the tokens sheet, when changing the size.
And please make sure the setting is actually set *and* saved.

**Comment by evilcj925** [comment]
I see.  I thought in the past it did it to the token already displayed,
but dragging a new tien out after making the change does have it shown

**Comment by Moerill** [comment]
> I see. I thought in the past it did it to the token already displayed
Token mold is and was all about changing stuff when *placing* tokens. You can though just reapply settings using the button in the quick settings.
