### ISSUE TITLE
[BUG] tokens no longer display - instead leave a blank square

### ISSUE THREAD

**Issue by gamehealthlife** [Moerill/token-mold#75]
**Describe the bug**
There are no console errors, but when a token is dragged into certain scenes it doesn't load. If it's dragged into some scenes though it works fine. I'm running the Rime of the Frostmaiden module and it doesn't work for any of the "Ten Towns" scenes which are maps of a town. I have used the VTTA assets importer to import these. However it does load into the more usual battle maps.

**Expected behavior**
I expect the token to appear

**Module incompatibilities**
I haven't found a clash - when I ran find the culprit the error only occurred when this module was selected.

![image](https://user-images.githubusercontent.com/75550254/101268582-6c64db00-375c-11eb-9ae2-81fa933b360d.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - FVTT Version [0.7.7]
 - Module version [Version 2.11.0]

**Comment by Moerill** [comment]
could you please check a few things:
a) Select the token, go into the config and check at which size the "scale" is set
b) Check in the scene config to which size the grid scale (distance and units) is set
c) test with "Set Token size to creature size and scaled to map scale" disabled. (token mold config)

**Comment by gamehealthlife** [comment]
a) In the scenes where the issue is, the tokens scale is set to 0.05 for some reason (normally it's set to 1 in which case it works properly)
b) 100 ft
c) Yep with that done it gets put to the right size

**Comment by Moerill** [comment]
kind of funny that this issue didn't occur before, since that is probably present since the dawn of this feature (>1year or so) :thinking: 

i'll add some minimum value + probably disable it for gridless maps (cause.. since no grid is there, token size doesn't matter)

**Comment by Moerill** [comment]
also thanks for checking and replying!
