### ISSUE TITLE
[BUG] Localized text is missing in release 2.11.0

### ISSUE THREAD

**Issue by adotor** [Moerill/token-mold#76]
**Describe the bug**
Localized text is missing. Instead the config page shows only the variable names only. 

The lang-Files are missing inside the released 2.11.0.zip. Ths version is still listed as latest version in foundry.

**To Reproduce**
Install 2.11.0 via Foundry.

**Expected behavior**
Text is shown. Lang files are delivered via distribution.

**Module incompatibilities**
 - FVTT Version 0.7.8
 - Module version 2.11.0

**Additional context**
The lang-Files are missing in the 2.11.0.zip. 2.11.1 is complete and works again.

**Comment by Moerill** [comment]
yup, thats the reason 2.11.1 exists, since i failed adding them in 2.11.0
