### ISSUE TITLE
[BUG] Error during startup

### ISSUE THREAD

**Issue by adotor** [Moerill/token-mold#77]
**Describe the bug**
When I start a world with the freshly installed module I get following error:

```
Uncaught (in promise) Error: ENOENT: no such file or directory, rename 'foundrydata/Data/modules/token-mold/assets/adjectives.db~' -> 'foundrydata/Data/modules/token-mold/assets/adjectives.db'
foundry.js:3777:46
    initHooks https://myHost:30000/modules/token-mold/scripts/token-mold.js:60
    AsyncFunctionThrow self-hosted:678
    (Async: async)
    _call https://myHost:30000/scripts/foundry.js:2496
    callAll https://myHost:30000/scripts/foundry.js:2456
    setupGame https://myHost:30000/scripts/foundry.js:6565
    InterpretGeneratorResume self-hosted:1468
    AsyncFunctionNext self-hosted:674
    (Async: async)
    _initializeGameView https://myHost:30000/scripts/foundry.js:7314
    initialize https://myHost:30000/scripts/foundry.js:6476
    InterpretGeneratorResume self-hosted:1468
    AsyncFunctionNext self-hosted:674
    (Async: async)
    <anonym> https://myHost:30000/scripts/foundry.js:7444
    AsyncFunctionNext self-hosted:674
    (Async: async)
    <anonym> https://myHost:30000/scripts/foundry.js:7442
```

This does not affect functionality. The adjective compendium is loaded and I can use it to generate names.

Game System used is: DCC
Core Language Setting is: German

**To Reproduce**
1. Install Module
2. Run a Game

**Expected behavior**
No error message.

**Module incompatibilities**
All modules deactivated.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 83.0 (current latest)
 - FVTT Version 0.7.8
 - Module version 2.11.1

**Comment by Moerill** [comment]
which system is "DCC"?

I do kind of wonder, i stumbled upon this kind of error in other modules, mostly when multiple modules try to access a compendium at the "same" time and thus is kinda difficult to prevent. (At least it felt like that was the pattern) With token mold alone it shouldnt happen (anymore).
Though more importantly: Does this impact the functionality? Can you reproduce it reliably? (cause i couldn't before)

In my experience this should/could happen only once after starting a world and shouldn't impact the game at all (or at least not after a page  refresh)

**Comment by adotor** [comment]
DCC is Dungeon Crawl Classics

https://github.com/cyface/foundryvtt-dcc

Functionality is not affected, I can still generate names with adjectives.

I get this message once at every start of a clean DCC game with only Token Mold active.

Thanks for your hint I will debug further and post any new pieces if knowledge.

**Comment by adotor** [comment]
I tried to debug and analyze what happens in foundry to trigger this error:
It is the result of a socket message, that is dispatched when the client connects to the game.

```
static dispatch(eventName, request) {
  ...
  game.socket.emit(eventName, request, response => {
    ... # error handlng happens here
  })
  ...
}
```
With following payload
```
eventName: "modifyCompendium"
request: {…}
  ​action: "get"
​  data: {}
    <prototype>: {…}
​  options: {…}
​​    returnType: "index"
​​    <prototype>: {…}
​    type: "token-mold.adjectives"
​  <prototype>: {…}
response: {…}
​  error: {…}
​​    class: "ServerError"
​​    message: "ENOENT: no such file or directory, rename 'foundrydata/Data/modules/token-mold/assets/adjectives.db~' -> 'foundrydata/Data/modules/token-mold/assets/adjectives.db'"
​​stack: "Error: ENOENT: no such file or directory, rename 'foundrydata/Data/modules/token-mold/assets/adjectives.db~' -> 'foundrydata/Data/modules/token-mold/assets/adjectives.db'"
​​    <prototype>: {…}
​  request: {…}
​  userId: ...
​  <prototype>: {…}
```

**Comment by Geekswordsman** [comment]
This error seems to be gone in Foundry v0.8.9, DCC v0.31.1.  If this error still is present, recommendation is to upgrade your Foundry and DCC system.
