### ISSUE TITLE
[FEATURE] Token type and unique name.

### ISSUE THREAD

**Issue by spencerthayer** [Moerill/token-mold#78]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
I would like to add names to actor tokens and keep their original name. For example "Archer – Frank." I would also like to customize how I have this displayed. Maybe it would be "An Archer named Frank," or just "Archer : Frank" whatever. 

**Describe alternatives you've considered**
Not sure there is an alternative.

**Additional context**
No. But I am going to look at the code tomorrow to see how this can be done. I just wanted to get a ticket made first.

**Comment by Geekswordsman** [comment]
#53

**Comment by Geekswordsman** [comment]
Marking this as duplicate and closing.
