### ISSUE TITLE
TM is overriding Prototype Token settings while nominally disabled

### ISSUE THREAD

**Issue by unsoluble** [Moerill/token-mold#8]
When Token Mold is enabled, but all of its application controls are disabled — i.e., none of Name, HP, Config, or Overlay are checked — any actors dragged to a scene will ignore any image settings in their Prototype Token config.

Example: Prototype Token is set to Width 1, Height 2; Scale 1.5. Without TM enabled, token drops with those settings. _With_ TM enabled (but options disabled), token drops at Width/Height of 1, and Scale of 1.0.

**Comment by Moerill** [comment]
are you sure you disabled automatic scaling of tokens for DnD 5e?
cause thats the only way i can reproduce it, by enabling that option.
I should maybe make it more clear, that that specific option is *independent* of the quick settings...
