### ISSUE TITLE
[BUG] Tokens not resizing

### ISSUE THREAD

**Issue by PupperooX** [Moerill/token-mold#80]
**Tokens not resizing in PF2E**
Also post console errors (F12 for most browsers) here that occur.

**To Reproduce**
All mods unchecked aside from Token mold.

**Expected behavior**
Changing an actor/ token to large should update the size to large.

**Screenshots/GIFs/Videos**
Console shot
![image](https://user-images.githubusercontent.com/67825695/102714647-03d33d80-42c8-11eb-8cd9-5eec16bb336e.png)

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser Chrome
 - FVTT Version 0.78
 - Module version 2.11.1

**Comment by PupperooX** [comment]
![image](https://user-images.githubusercontent.com/67825695/102714680-3c731700-42c8-11eb-9c61-2f7c3ae3ad15.png)

**Comment by Geekswordsman** [comment]
Unable to reproduce issue in Foundry v0.8.9 and pf2e v2.19.3.9074.  Tokens size correctly, and resize if creature size on the token's sheet is changed.
