### ISSUE TITLE
[FEATURE] Use Table for auto Loot

### ISSUE THREAD

**Issue by jseaz73** [Moerill/token-mold#84]
When a mob dies, use a loot table to determine any coin added or random items.   

Think Cascading tables... maybe based on MOB CR...
 
**CRXX_LOOT-Table**
CR0
CR1
...
CR30

**CR1Loot-Table**
5% 1-2 Plat
10% 5-10 Gold
25% Club
60% Box of junk .

**Comment by Moerill** [comment]
Thanks for the feature request.
Dieing mobs is not really in scope of this module.

What theoretically could be done is doing smth like this on creation, populating tokens with some random stuff. (Or do some randomization on attributes) Which would be a very nice to have, but is not trivial, especially for a system agnostic way and from a UX perspective.

Its not something i plan to do. If someone wants to tackle this, feel free to send me a PR and/or discuss here (or in another issue) on some ideas on how to implement it.
