### ISSUE TITLE
Random Mirroring not Working

### ISSUE THREAD

**Issue by AntJLopez** [Moerill/token-mold#85]
I have isolated this issue by having Token Mold installed and no other module. Tokens are not mirrored (horizontally or vertically), despite both being checked in settings. Other features (such as random adjective prefixes) are working. I am using the latest versions: Foundry 0.7.9 and Token Mold 2.11.1.

Is this a bug, or am I making a user error?

**Comment by Geekswordsman** [comment]
The setting will only work if the Overwrite Config is checked under the Token Mold heading.

**Comment by Geekswordsman** [comment]
Due to time since this was opened, closing as non-issue (can be re-opened if necessary).
