### ISSUE TITLE
"Curated English" adjective list has some bizarre entries

### ISSUE THREAD

**Issue by gitmon1234** [Moerill/token-mold#92]
The "English - smaller but curated set of 700" random adjective list has some bizarre inclusions like "Mens' Rights Compliant".
Seems like the curated list could use an editing pass to check that the adjectives are on-theme for a fantasy rpg VTT.

**Comment by Moerill** [comment]
Ye.. Especially "Men's rights" feels off.
But its a community curated list provided by the community. So feel free to give it a pass and send me a new and better version to be included in future versions. 
On a sidenote: its not supposed to be a fantasy themed list, its supposed to be a generic rpg themed list (for a generic vtt program). if you want to provide a purely fantasy curated list, feel free to send it to me and i'll include it as well!

**Comment by Moerill** [comment]
Skimming through the list i'm not confident enough in my english skills to curate it myself.  
But i've removed "Men's rights" (this feels off and completly wrong.) scheduled for the next update.
