### ISSUE TITLE
[BUG] 0.8.6 Error | 

### ISSUE THREAD

**Issue by webmaster94** [Moerill/token-mold#95]
In 0.8.6, the module does not seem to function at all.

This error is thrown to the console on startup:
![image](https://user-images.githubusercontent.com/85364225/120927966-65396e00-c6a8-11eb-851a-5d8b9c353fd5.png)

I see the following error in the console when tokens are dragged onto the map:
![image](https://user-images.githubusercontent.com/85364225/120927812-ce6cb180-c6a7-11eb-8689-72897dbbd67a.png)

No other modules were enabled when reproducing the behavior. 

 - OS: Windows 10
 - I am using the Foundry Standalone App
 - FVTT Version 0.8.6
 - Module version v2.13

**Comment by Moerill** [comment]
What system are you using?

**Comment by webmaster94** [comment]
DnD5e latest release.

**Comment by Moerill** [comment]
I'm confused. Your screenshot do reference lines of code that have nothing to do with the existing issue.   
It reads like for some reason your javascript file is faulty. Please try reinstalling the module and report back whether the issue persists.

**Comment by Moerill** [comment]
> No other modules were enabled when reproducing the behavior.

is at least not correct for the provided screenshots btw. Its referencing libwrapper there, which is a module.

**Comment by webmaster94** [comment]
I do apologize, I still had libwrapper and socketlib activated in my test world as I was testing out another module that relied on them and I forgot to disable them when I disabled the other module. After uninstalling/reinstalling Token Mold, like you suggested, it appears to have fixed the problem. It was still occurring with those modules disabled before I uninstalled/reinstalled.
