### ISSUE TITLE
[BUG] HP rolls are no longer private in VTT 0.8.6

### ISSUE THREAD

**Issue by ullantra** [Moerill/token-mold#98]
Per title - updated to 0.8.6 today and understand that this might be getting fixed in "3.0", but Token Mold no longer outputs the HP rolls in chat automatically to GM only (it goes to whatever setting you have active at the time). Previously, I would have Public Roll selected by default and it would roll HP privately per your main page image showing that functionality.
Now, the hp rolls including the formula are publicly visible unless I manually change to Private GM Roll before dragging a new token onto a scene.
Disabling reporting to chat in the settings window works, but I really like the effect on my players that "GM rolled some dice" had along with the noise..

I am going through working out if any other module is causing a clash, but have not found anything yet. Will update ticket if I find anything.

Also, I don't think the overlay is working in 0.8.6 (didn't use this feature before so not 100% on this)

**Comment by Geekswordsman** [comment]
This was a system issue in D&D 5e as a result of core updates to Foundry back in v0.8.6 and has since been resolved; closing issue.

**Comment by Cussa** [comment]
Can we reopen this issue? The HP rolls are going public.

![image](https://user-images.githubusercontent.com/912710/156551213-978e4bbf-1a43-49c7-85d6-84d9f9f98d9e.png)

To roll privately, I have to change the configuration of the roll in the chat before adding the monsters in the scene.
